name: Daily Game Report

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행 (UTC 기준)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Run script
      run: python nin_report_v1.py

    - name: Commit and push report
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add report_*.csv
        git commit -m "Add daily game report for $(date +%Y%m%d)" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}